services:
  webserver:
    build: {}
    environment:
      - SERVER_NAME="www.docker.test"
      - SERVER_ADMIN="webmaster@docker.test"
    volumes:
      - ./rootfs/www/:/www/
    ports:
      - 8000:80

networks:
  default:
    name: internal
    external: true